name: test

on: [ push ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install imagemagick
        run: |
          sudo apt install imagemagick
          sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml

      - name: Install patchouli
        run: |
          sudo npm run build
          sudo npm i -g . --unsafe-perm

      - name: Install mocha globally
        run: sudo npm i -g mocha

      - name: Run tests
        run: npm test

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: integration
          path: test/integration/artifacts/

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: success() && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kotborealis/patchouli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./docker/Dockerfile
